data:
  - path: <YOUR PATH TO G-OPD-Training-Data/DeepMath-103K/offline_data_balanced.jsonl>
    teacher: math
  - path: <YOUR PATH TO G-OPD-Training-Data/Eurus/offline_data_balanced.jsonl>
    teacher: code
